version: '3'
services:
  bot:
    image: maxswjeon/certmanager:0.5
    hostname: authentication-bot
    container_name: authentication_bot
    restart: always
    environment:
      - BOT_TOKEN=${BOT_TOKEN}
      - CA_PASS=${CA_PASS}
      - DATABASE_PATH=${DATABASE_PATH}
      - DISCORD_CHANNELS=${DISCORD_CHANNELS}
      - ENFORCE_STRONG_KEYS=${ENFORCE_STRONG_KEYS}
      - CERTIFICATE_VALID_DAYS=${CERTIFICATE_VALID_DAYS}
    volumes:
      - /etc/ssh/ca_user_key:/root/ca_user_key
      - /etc/ssh/ssh_revoked_keys:/root/ssh_revoked_keys
